data:
    dataset: "AllWeather"
    image_size: 64
    channels: 3
    num_workers: 32 #32
    # 数据存放路径
    data_dir: "E:\\deeplearning\\weather_diffusion"
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    patch_n: 16
    batch_size: 4
    n_epochs: 1775 
    # 1775
    n_iters: 2000000
    # 记录模型频率
    snapshot_freq: 1000
    # 验证模型频率
    validation_freq: 10000

sampling:
    batch_size: 16
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    amsgrad: False
    eps: 0.00000001
